# Vault server
[Vault]
Addr = "http://localhost:8200"

# Vault init process
[Init]
NumKeys = 5

[Init.CredsSecret]
Name = "prod-vault-controller-managed-creds"
Namespace = "kscout"
Labels = { app = "vault", component = "controller", env = "prod" }

# User authentication
[Auth.GitHub.Method]
Organization = "kscout"

[Auth.GitHub.TeamPolicies]
developers = "developers"
