apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.resource-name" . }}-controller
  labels:
{{ include "vault.resource-labels" . | indent 4 }}
    component: controller
spec:
  clusterIP: None
  selector:
{{ include "vault.resource-labels" . | indent 4 }}
    component: controller
