apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vault.resource-name" . }}
  labels:
{{ include "vault.resource-labels" .  | indent 4 }}
    component: vault
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "vault.resource-labels" . | indent 6 }}
      component: vault
  serviceName: {{ include "vault.resource-name" . }}
  template:
    metadata:
      labels:
{{ include "vault.resource-labels" . | indent 8 }}
        component: vault
      annotations:
        {{- range $path, $_ := .Files.Glob "config/vault/*" }}
        config-{{ $path | base }}-sha256sum: {{ tpl ($.Files.Get $path) $ | sha256sum }}
        {{- end }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "vault.resource-name" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "vault.resource-name" . }}-data
      containers:
        - name: vault
          image: vault
          command:
            - vault
            - server
          env:
            - name: SKIP_SETCAP
              value: "true"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VAULT_CLUSTER_ADDR
              value: "http://$(POD_IP):8201"
          args:
            - "--config=/mnt/config/server.hcl"
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: data
              mountPath: {{ .Values.vault.dataMount }}
          ports:
            - name: http
              containerPort: 8200
            - name: cluster-address
              containerPort: 8201
          livenessProbe:
            httpGet:
              path: '/v1/sys/health?standbyok=true&uninitcode=200&uninitcode=200'
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: '/v1/sys/health?standbyok=true&uninitcode=200&uninitcode=200'
              port: http
              scheme: HTTP
