apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vault.resource-name" . }}-data
  labels:
{{ include "vault.resource-labels" . | indent 4 }}    
    component: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
