apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.resource-name" . }}-config
  labels:
{{ include "vault.resource-labels" . | indent 4 }}
    component: vault
data:
  {{- range $path, $_ := .Files.Glob "config/vault/*" }}
  {{ $path | base }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
  
