apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vault.resource-name" . "vault-config" }}
  labels:
{{ template "vault.resource-labels" . "vault" | indent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "config/vault/*" }}
  {{ $path | base }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
  
