apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}
  labels:
{{ template "vault.resource-labels" . "vault" | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ template "vault.resource-labels" . "vault" | indent 6 }}
  serviceName: {{ template "vault.resource-name" . }}
  template:
    metadata:
      labels:
{{ template "vault.resource-labels" . "vault" | indent 8 }}
      annotations:
        {{- range $path, $_ := .Files.Glob "config/vault/*" }}
        config-{{ $path | base }}-sha256sum: {{ tpl ($.Files.Get $path) $ | sha256sum }}
        {{- end }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "vault.resource-name" . "vault-config" }}
      containers:
        - name: vault
          image: vault
          args:
            - "--config=/vault/config/server.hcl"
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /vault/config/
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: '/sys/health?standbycode=200&drsecondarycode=200&performancestandbycode=200&sealedcode=200&uninitcode=200'
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: '/sys/health?standbycode=200&drsecondarycode=200&performancestandbycode=200&sealedcode=200&uninitcode=200'
              port: http
              scheme: HTTP
