apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.resource-name" . }}
  labels:
{{ include "vault.resource-labels" .  | indent 4 }}
    component: vault
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8200
  selector:
{{ include "vault.resource-labels" . | indent 4 }}
    component: vault
