apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "vault.resource-name" . }}
  labels:
{{ include "vault.resource-labels" . | indent 4 }}
    component: vault
spec:
  host: {{ .Values.vault.host }}
  path: /
  to:
    kind: Service
    name: {{ include "vault.resource-name" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
status:
  ingress:
    - host: {{ .Values.vault.host }}
