apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.resource-name" . }}
  labels:
{{ template "vault.resource-labels" . "vault" | indent 4 }}
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  selector:
{{ template "vault.resource-labels" . "vault" | indent 4 }}
