apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.resource-name" . }}
  labels:
{{ include "vault.resource-labels" .  | indent 4 }}
    component: vault
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
{{ include "vault.resource-labels" . | indent 4 }}
    component: vault
